export const REQUEST = 'API/REQUEST';
export const REQUEST_START = 'API/REQUEST_START';
export const REQUEST_SUCCESS = 'API/REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'API/REQUEST_FAILURE';
export const REQUEST_END = 'API/REQUEST_END';
